services:
  optimizer:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
    - 80:80
    - 443:443
    #volumes:
    #- /path/to/your/key:/etc/nginx/nginx.key
    #- /path/to/your/cert:/etc/nginx/nginx.crt
    environment:
      - TARGET=your_fqdn_or_ip

