services:
  optimizer:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
    - 2080:80
    - 2443:443
    #volumes:
    #- /path/to/your/key:/etc/nginx/nginx.key
    #- /path/to/your/cert:/etc/nginx/nginx.crt
    environment:
      - TARGET=http://www.thephantomx.com

